// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzkqrjzahurxhmembqrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6a3FyanphaHVyeGhtZW1icXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDYyMzcsImV4cCI6MjA3NDM4MjIzN30.xfrpn7i0e76RqeK1RlaGcngESfdw3BoAN7kUg6nlBN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});